apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro
  namespace: default
spec:
  replicas: 2 # Number of replicas
  selector:
    matchLabels:
      app: vpro
  template:
    metadata:
      labels:
        app: vpro
    spec:
      containers:
        - name: vpro
          image: asif1008/repo1:vp.1
          ports:
            - containerPort: 8080 # Port 80
