apiVersion: v1
kind: Service
metadata:
  name: vpro-svc
spec:
  type: LoadBalancer
  selector:
    app: vpro
  ports:
  - protocol: TCP
    port: 80          # This is the port exposed to the outside world
    targetPort: 8080
    nodePort: 32151
